### ISSUE TITLE
Dropdown opens automatically

### ISSUE THREAD

**Issue by lucasrohers** [use-bootstrap/use-bootstrap-select#4]
I'm using bootstrap 5.3
The dropdown button opens automatically when I hover the mouse.
How can I make it so that it only opens when clicked?

**Comment by erwinheldy** [comment]
I have updated the demo page with Bootstrap 5.3 and it's running as usual.

**Comment by lucasrohers** [comment]
The problem occurs because you use dropdown. If you have set native in bootstrap for the dropdown to appear when the mouse is hovered, the bug occurs.
The suggestion is to make the class independent.

**Comment by erwinstone** [comment]
In Bootstrap, dropdown menus are designed to be activated on click by default. However, you can achieve the hover effect with a little bit of custom CSS
```css
/* Show dropdown on hover */
.dropdown:hover .dropdown-menu {
  display: block;
}
```

If you want to exclude certain dropdowns from the hover effect based on a specific class (in this case, ".use-bootstrap-select"), you can modify the CSS selector to exclude elements with that class. Here's how you can do it:
```css
/* Show dropdown on hover, excluding dropdowns with class .use-bootstrap-select */
.dropdown:not(.use-bootstrap-select):hover .dropdown-menu {
  display: block;
}
```

**Comment by erwinheldy** [comment]
In Bootstrap, dropdown menus are designed to be activated on click by default. However, you can achieve the hover effect with a little bit of custom CSS
```css
/* Show dropdown on hover */
.dropdown:hover .dropdown-menu {
  display: block;
}
```

If you want to exclude certain dropdowns from the hover effect based on a specific class (in this case, ".use-bootstrap-select"), you can modify the CSS selector to exclude elements with that class. Here's how you can do it:
```css
/* Show dropdown on hover, excluding dropdowns with class .use-bootstrap-select */
.dropdown:not(.use-bootstrap-select):hover .dropdown-menu {
  display: block;
}
```
